# KITTI monocular model for seq.00-02

#==============#
# Camera Model #
#==============#

Camera.name: "test name"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fx: 643.193173
Camera.fy: 641.053741
Camera.cx: 334.442766
Camera.cy: 235.263927

Camera.k1: -0.025462
Camera.k2: 0.071908
Camera.p1: 0.004506
Camera.p2: -0.004357
Camera.k3: 0.000000

Camera.fps: 30.0  # please reconfigure according to your camera
Camera.cols: 640
Camera.rows: 480

Camera.color_order: "RGB"  # please reconfigure according to your camera

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer.keyframe_size: 0.06
PangolinViewer.keyframe_line_width: 1
PangolinViewer.graph_line_width: 1
PangolinViewer.point_size: 2
PangolinViewer.camera_size: 0.07
PangolinViewer.camera_line_width: 2
PangolinViewer.viewpoint_x: 0
PangolinViewer.viewpoint_y: -20
PangolinViewer.viewpoint_z: -0.1
PangolinViewer.viewpoint_f: 2800
