# KITTI monocular model for seq.00-02

#=====================#
# Galaxy S8 - mirella #
#=====================#

Camera.name: "test name"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fx: 1853.47996
Camera.fy: 1853.3963
Camera.cx: 933.738824
Camera.cy: 500.381923

Camera.k1: 0.209280120
Camera.k2: -1.03926982
Camera.p1: -0.00330698922
Camera.p2: -0.00218026201
Camera.k3: 2.51916583

Camera.fps: 20.0  # please reconfigure according to your camera
Camera.cols: 1080
Camera.rows: 1920

Camera.color_order: "RGB"  # please reconfigure according to your camera

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 10000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer.keyframe_size: 0.06
PangolinViewer.keyframe_line_width: 1
PangolinViewer.graph_line_width: 1
PangolinViewer.point_size: 2
PangolinViewer.camera_size: 0.07
PangolinViewer.camera_line_width: 2
PangolinViewer.viewpoint_x: 0
PangolinViewer.viewpoint_y: -20
PangolinViewer.viewpoint_z: -0.1
PangolinViewer.viewpoint_f: 2800
